### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by jparis** [eapowertools/qmcu-app-mover#11]
Cross post from QMC Utilities issue list:

"Trying to move one or several apps between two servers (1 in the cloud) did not work, I tried both directions. Reading the apps from the respective source servers works (so certificates are set up correctly within the cert sub-folder), but the "Deploy" button seems to have no effect. No error message or any kind of feedback apears."

https://github.com/eapowertools/QlikSenseQMCUtility/issues/41

**Comment by jparis** [comment]
Sorry for the delay @mhr2015, we now have a logging framework and I've updated the plugin to provide some output. Feel free to give it a try and let me know how it works.

Also @ahsyed, you can try the updated plugin here.

**Comment by jparis** [comment]
Let me know if you need help setting up the new plugin. You should be able to just grab the appMover folder in this repository and drop it into the 'plugins' folder in QlikSenseQMCUtilities, leave the node_modules packages that's already there in place.

**Comment by ahsyed** [comment]
Adding the updated version of the App Mover displays nothing. Please see the attached.

![image](https://cloud.githubusercontent.com/assets/6596705/22892242/da609af2-f1df-11e6-809b-14318d6faab2.png)

**Comment by jparis** [comment]
Ah yes... We don't have the newest version of QMC utilities available as an installer. The best way would be to grab the latest code and drop it in place then run both `bower install` and `npm install`. You can ping me on here and I can walk you through it via WebEx or something if you want.

**Comment by ahsyed** [comment]
Thanks Jesse, Please let me know the details.

**Comment by jparis** [comment]
email me at 

```jesse.paris
at
qlik
dot
com```

**Comment by gustafssone** [comment]
Hi Jesse,

Can you add the commands to do this? Node.js isn't installed, but it is bundled with EA PowerTools I guess. What do I need to do to add the latest source code besides downloading it and unpacking to C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities?

Cheers,
Erik

**Comment by jparis** [comment]
We actually have an installer coming soon (today or tomorrow), so I'll just post up here when the link is up. Or ping me offline if you want, you know where to find me.

**Comment by gustafssone** [comment]
@goldbergjeffrey is already ahead of you @jparis ;) https://github.com/eapowertools/QlikSenseQMCUtility/releases/tag/2.0.2

**Comment by gustafssone** [comment]
btw, just tested this in the latest version, downloaded the newest installer of QMC Utility 2.0.2 and Qlik Sense 3.2 - same issue. Certificates and trust work (as I can connect to both local and remote QMC), but it gets stuck at "Trying to deploy apps." in the output.

No file at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\plugins\appMover\temp . Nothing particular in the logs - can I add extended login somewhere?

**Comment by rmterenzi** [comment]
Hi Eric,

Try to ensure those last two directories are created and if not, generate them and try again. Also there should be a "certs" folder in appmover\ ...is that one also there?

-Michael

**Comment by rmterenzi** [comment]
@gustafssone Erik (typo on the "c"). I still do that after all these years

**Comment by gustafssone** [comment]
@rmterenzi yepp certs is there and filled up with both local and remote certs. I can load the app list on local AND remote server, meaning connection is valid. 
Which "two directories" are you referring to?

**Comment by jparis** [comment]
@ahsyed The installed has been updated and is now at https://github.com/eapowertools/QlikSenseQMCUtility/releases/tag/2.0.2

**Comment by jparis** [comment]
ping me on email or skype erik and we'll chat. I'm curious now.

**Comment by ahsyed** [comment]
I am still having issues with the new Installer. I am getting the output as
'Trying to deploy apps' forever.

**Comment by jparis** [comment]
Didn't see this on my machine, but managed to reproduce it on another. Will fix it and let you know when I've updated the code.

**Comment by ahsyed** [comment]
Thanks for the update and replicating the issue.

**Comment by jparis** [comment]
You will need to update your routes.js folder at `C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\plugins\appMover\routes.js` with `https://github.com/eapowertools/qmcu-app-mover/blob/master/appMover/routes.js`.

Also, qrs-interact at `C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\plugins\appMover\node_modules\qrs-interact` with this module: `https://github.com/eapowertools/qrs-interact`. Basically `qrsInteract.js`, `qrsInteractFactory.js` and `common.js` need to be replaced.

**Comment by gustafssone** [comment]
It works!!

Trying to deploy apps.
Done creating temporary directory.
Setting up node to send application to.
Getting app(s) from: <localserver>
Temporarily writing app to local disk.
Retrieved app 'mats test(1)'.
Trying to upload app 'mats test(1)' to: <remoteserver>
Upload of 'mats test(1)' complete to all nodes.


Best regards
Erik Gustafsson

**Comment by jparis** [comment]
Closing this.
