### ISSUE TITLE
Appmover subdirectories not created automatically 

### ISSUE THREAD

**Issue by rmterenzi** [eapowertools/qmcu-app-mover#15]
In the latest version @goldbergjeffrey I couldn't use app mover and got the errors below. Turns out the directories \appmover\certs were missing. Once I added them and placed the certs in there it worked good.

**Comment by rmterenzi** [comment]
![img_0610](https://cloud.githubusercontent.com/assets/19998953/23066360/311dca4e-f4e8-11e6-804f-bd7b27b798b9.JPG)

**Comment by jparis** [comment]
Closing this...
